# Site settings
title: Circulation | Exchange
subtitle: Moving Images in Contemporary Art
description: "Circulation Exchange is an online publication dedicated to artists exploring innovative and creative intersections of photography and social media. It will feature interviews, short critical essays on specific projects and historical precedents, and notable work made on and about specific social media platforms. Supported by the Creative Capital | Warhol Foundation Arts Writers Grant Program"
baseurl: "http://circulationexchange.org" # the subpath of your site, e.g. /blog/
url: "http://circulationexchange.org"
twitter_username:
permalink: none

# Build settings
markdown: kramdown
